package Thivi.Project.Gobi.Dreams.service;

import Thivi.Project.Gobi.Dreams.dto.PaymentDTO;
import Thivi.Project.Gobi.Dreams.entity.Payment;
import Thivi.Project.Gobi.Dreams.mapper.EntityMapper;
import Thivi.Project.Gobi.Dreams.repository.PaymentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class PaymentService {

    private final PaymentRepository paymentRepository;
    private final EntityMapper entityMapper;

    @Autowired
    public PaymentService(PaymentRepository paymentRepository, EntityMapper entityMapper) {
        this.paymentRepository = paymentRepository;
        this.entityMapper = entityMapper;
    }

    public PaymentDTO createPayment(PaymentDTO paymentDTO) {
        Payment payment = new Payment(null, // ID will be generated by JPA
                null, // Booking will be set later
                paymentDTO.getAmount(),
                paymentDTO.getPaymentDate(),
                paymentDTO.getPaymentMethod());
        Payment savedPayment = paymentRepository.save(payment);
        return entityMapper.paymentToPaymentDTO(savedPayment);
    }

    public List<PaymentDTO> getAllPayments() {
        List<Payment> payments = paymentRepository.findAll();
        return payments.stream()
                .map(entityMapper::paymentToPaymentDTO)
                .collect(Collectors.toList());
    }

    public PaymentDTO getPaymentById(Long id) {
        Payment payment = paymentRepository.findById(id).orElseThrow(() -> new RuntimeException("Payment not found"));
        return entityMapper.paymentToPaymentDTO(payment);
    }
}
