package Thivi.Project.Gobi.Dreams.service;

import Thivi.Project.Gobi.Dreams.dto.PhotoDTO;
import Thivi.Project.Gobi.Dreams.entity.Photo;
import Thivi.Project.Gobi.Dreams.mapper.EntityMapper;
import Thivi.Project.Gobi.Dreams.repository.PhotoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class PhotoService {

    private final PhotoRepository photoRepository;
    private final EntityMapper entityMapper;

    @Autowired
    public PhotoService(PhotoRepository photoRepository, EntityMapper entityMapper) {
        this.photoRepository = photoRepository;
        this.entityMapper = entityMapper;
    }

    public PhotoDTO uploadPhoto(PhotoDTO photoDTO) {
        Photo photo = new Photo(null, // ID will be generated by JPA
                null, // Booking will be set later
                photoDTO.getFilePath(),
                photoDTO.getUploadedDate());
        Photo savedPhoto = photoRepository.save(photo);
        return entityMapper.photoToPhotoDTO(savedPhoto);
    }

    public List<PhotoDTO> getAllPhotos() {
        List<Photo> photos = photoRepository.findAll();
        return photos.stream()
                .map(entityMapper::photoToPhotoDTO)
                .collect(Collectors.toList());
    }

    public PhotoDTO getPhotoById(Long id) {
        Photo photo = photoRepository.findById(id).orElseThrow(() -> new RuntimeException("Photo not found"));
        return entityMapper.photoToPhotoDTO(photo);
    }
}
