package Thivi.Project.Gobi.Dreams.service;

import Thivi.Project.Gobi.Dreams.dto.RatingDTO;
import Thivi.Project.Gobi.Dreams.entity.Rating;
import Thivi.Project.Gobi.Dreams.mapper.EntityMapper;
import Thivi.Project.Gobi.Dreams.repository.RatingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class RatingService {

    private final RatingRepository ratingRepository;
    private final EntityMapper entityMapper;

    @Autowired
    public RatingService(RatingRepository ratingRepository, EntityMapper entityMapper) {
        this.ratingRepository = ratingRepository;
        this.entityMapper = entityMapper;
    }

    public RatingDTO addRating(RatingDTO ratingDTO) {
        Rating rating = new Rating(null, // ID will be generated by JPA
                null, // Customer will be set later
                ratingDTO.getRating(),
                ratingDTO.getReview());
        Rating savedRating = ratingRepository.save(rating);
        return entityMapper.ratingToRatingDTO(savedRating);
    }

    public List<RatingDTO> getAllRatings() {
        List<Rating> ratings = ratingRepository.findAll();
        return ratings.stream()
                .map(entityMapper::ratingToRatingDTO)
                .collect(Collectors.toList());
    }

    public RatingDTO getRatingById(Long id) {
        Rating rating = ratingRepository.findById(id).orElseThrow(() -> new RuntimeException("Rating not found"));
        return entityMapper.ratingToRatingDTO(rating);
    }
}
